### ISSUE TITLE
Model trained using https://codelabs.developers.google.com/tflite-object-detection-android is failing when used in the android app.

### ISSUE THREAD

**Issue by bibinss** [googlecodelabs/odml-pathways#6]
## Expected Behavior
Android app should work with the tflight model trained using the notebook mentioned in https://codelabs.developers.google.com/tflite-object-detection-android

## Actual Behavior
Android app fails with the below error, when app is launched from android studio. Error is thrown when you click on the first image from the app launch page.

E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-1
    Process: org.tensorflow.codelabs.objectdetection, PID: 1308
    java.lang.AssertionError: Error occurred when initializing ObjectDetector: Output tensor at index 0 is expected to have 3 dimensions, found 2.
        at org.tensorflow.lite.task.vision.detector.ObjectDetector.initJniWithModelFdAndOptions(Native Method)
        at org.tensorflow.lite.task.vision.detector.ObjectDetector.access$000(ObjectDetector.java:86)
        at org.tensorflow.lite.task.vision.detector.ObjectDetector$1.createHandle(ObjectDetector.java:152)
        at org.tensorflow.lite.task.vision.detector.ObjectDetector$1.createHandle(ObjectDetector.java:145)
        at org.tensorflow.lite.task.core.TaskJniUtils$1.createHandle(TaskJniUtils.java:70)
        at org.tensorflow.lite.task.core.TaskJniUtils.createHandleFromLibrary(TaskJniUtils.java:91)
        at org.tensorflow.lite.task.core.TaskJniUtils.createHandleFromFdAndOptions(TaskJniUtils.java:66)
        at org.tensorflow.lite.task.vision.detector.ObjectDetector.createFromFileAndOptions(ObjectDetector.java:143)
        at org.tensorflow.codelabs.objectdetection.MainActivity.runObjectDetection(MainActivity.kt:127)
        at org.tensorflow.codelabs.objectdetection.MainActivity.access$runObjectDetection(MainActivity.kt:48)
        at org.tensorflow.codelabs.objectdetection.MainActivity$setViewAndDetect$1.invokeSuspend(MainActivity.kt:183)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
I/Process: Sending signal. PID: 1308 SIG: 9

## Steps to Reproduce the Problem

1. Follow the steps mentioned at https://codelabs.developers.google.com/tflite-object-detection-android
2. At step 7), instead of downloading the model, run the notebook to train the model.
3. After training the model from notebook, download the model.tflite from the notebook and copy to your android studio demo project (use the final project). 
4. Build the project and launch in simulator. 
5. Once app is launched, click on the first image displayed for object detection.
6. App fails with the error as mentioned below.

## Specifications

- Version:
- Platform:

**Comment by TannerGilbert** [comment]
Should be fixed by training the model with Tensorflow v2.5

**Comment by khanhlvg** [comment]
The final fix is out in the latest version of TFLite Support Library. Please update your build.gradle file to use the latest version as below. Now you can use TFLite model trained with the latest version of Model Maker (0.3.4) and run it using the latest version of TFLite Task Library.
`implementation 'org.tensorflow:tensorflow-lite-task-vision:0.3.1'`
